5.0.0

diff --git a/sys/unix/Makefile.top b/sys/unix/Makefile.top
--- a/sys/unix/Makefile.top
+++ b/sys/unix/Makefile.top
@@ -1,30 +1,35 @@
-#	NetHack Makefile.
-# NetHack 3.6  Makefile.top	$NHDT-Date: 1447844578 2015/11/18 11:02:58 $  $NHDT-Branch: master $:$NHDT-Revision: 1.32 $
+#      NetHack Top-level Makefile.
+# NetHack 5.0  Makefile.top    $NHDT-Date: 1722119081 2024/07/27 22:24:41 $  $NHDT-Branch: keni-fetchlua $:$NHDT-Revision: 1.109 $
+# Copyright (c) 2015 by Kenneth Lorber, Kensington, Maryland
+# NetHack may be freely redistributed.  See license for details.
 
-# Root of source tree:
+#	Root of source tree:  (Note: dot is after setup.sh has been used
+#	to create the active Makefiles from sys/unix/Makefile.*.
+#	It isn't sys/unix/ where you might happen to be reading this.)
 NHSROOT=.
 
-# newer makes predefine $(MAKE) to 'make' and do smarter processing of
-# recursive make calls if $(MAKE) is used
-# these makes allow $(MAKE) to be overridden by the environment if someone
-# wants to (or has to) use something other than the standard make, so we do
-# not want to unconditionally set $(MAKE) here
+#	Newer makes predefine $(MAKE) to 'make' and do smarter processing
+#	of recursive make calls if $(MAKE) is used.
+#	These makes allow $(MAKE) to be overridden by the environment if
+#	someone wants to (or has to) use something other than the standard
+#	make, so we do not want to unconditionally set $(MAKE) here.
 #
-# unfortunately, some older makes do not predefine $(MAKE); if you have one of
-# these, uncomment the following line
-# (you will know that you have one if you get complaints about unable to
-# execute things like 'data' and 'rumors')
+#	Unfortunately, some older makes do not predefine $(MAKE); if you
+#	have one of these, uncomment the following line.
+#	(You will know that you have one if you get complaints about unable
+#	to execute things like 'data' and 'rumors'.)
 # MAKE = make
 
-# make NetHack
+#	make NetHack (as opposite to variants or such)
 #PREFIX	 = /usr
 GAME     = nethack
+# GAME     = nethack.exe
 # GAME     = nethack.prg
 #GAMEUID  = games
 #GAMEGRP  = bin
 
-# Permissions - some places use setgid instead of setuid, for instance
-# See also the option "SECURE" in include/config.h
+#	Permissions - some places use setgid instead of setuid, for instance.
+#	See also the option "SECURE" in include/config.h.
 #GAMEPERM = 04755
 FILEPERM = 0644
 # VARFILEPERM = 0644
@@ -32,69 +37,148 @@ EXEPERM  = 0755
 DIRPERM  = 0755
 # VARDIRPERM = 0755
 
-# VARDIR may also appear in unixconf.h as "VAR_PLAYGROUND" else HACKDIR
+#	VARDIR may also appear in unixconf.h as "VAR_PLAYGROUND" else HACKDIR
 #
-# note that 'make install' believes in creating a nice tidy HACKDIR for
-# installation, free of debris from previous NetHack versions --
-# therefore there should not be anything in HACKDIR that you want to keep
-# (if there is, you'll have to do the installation by hand or modify the
-# instructions)
+#	Note well!  'make install' believes in creating a nice tidy HACKDIR
+#	for installation, free of debris from previous NetHack versions --
+#	therefore there should not be anything in HACKDIR that you want to
+#	keep (if there is, you'll have to do the installation by hand or
+#	modify the install commands below).
 #HACKDIR  = $(PREFIX)/games/lib/$(GAME)dir
 #VARDIR  = $(HACKDIR)
-# Where nethack.sh in installed.  If this is not defined, the wrapper is not used.
+#	Where nethack.sh is installed (as 'nethack').
+#	If this is not defined, the shell wrapper script is not used.
 #SHELLDIR = $(PREFIX)/games
 
+#	Extra data files depending upon the interface(s) built into nethack.
 # per discussion in Install.X11 and Install.Qt
-#VARDATND = 
-# VARDATND = x11tiles NetHack.ad pet_mark.xbm pilemark.xpm
-# VARDATND = x11tiles NetHack.ad pet_mark.xbm pilemark.xpm rip.xpm
-# for Atari/Gem
-# VARDATND = nh16.img title.img GEM_RSC.RSC rip.img
-# for BeOS
-# VARDATND = beostiles
-# for Gnome
-# VARDATND = x11tiles pet_mark.xbm pilemark.xpm rip.xpm mapbg.xpm
+# Qt prefers nhtiles.bmp but can use x11tiles, and it ignores NetHack.ad.
+# X11 uses those last two.
+# Both can display a conventional text map instead of tiles.
+#	tty and/or curses (no extra data files outside of the dlb container):
+#VARDATND =
+#	All X11 and/or Qt variations may also include tty or curses or both):
+#	X11 without Qt:
+# VARDATND = x11tiles NetHack.ad pet_mark.xbm pilemark.xbm
+#	X11 with GRAPHIC_TOMBSTONE (requires 'xpm'):
+# VARDATND = x11tiles NetHack.ad pet_mark.xbm pilemark.xbm rip.xpm
+#	both X11 and Qt:
+# VARDATND = x11tiles nhtiles.bmp NetHack.ad pet_mark.xbm pilemark.xbm rip.xpm
+#	Qt without X11; assumes GRAPHIC_TOMBSTONE:
+# VARDATND = nhtiles.bmp pet_mark.xbm pilemark.xbm rip.xpm
 
-VARDATD = bogusmon data engrave epitaph oracles options quest.dat rumors
+VARDATD = bogusmon data engrave epitaph oracles options quest.lua rumors
 VARDAT = $(VARDATD) $(VARDATND)
 
-# Some versions of make use the SHELL environment variable as the shell
-# for running commands.  We need this to be a Bourne shell.
+#	Some versions of make use the SHELL environment variable as the
+#	shell for running commands.  We need this to be a Bourne shell.
 # SHELL = /bin/sh
-# for Atari
+# for Atari (obsolete)
 # SHELL=E:/GEMINI2/MUPFEL.TTP
 
 # Commands for setting the owner and group on files during installation.
 # Some systems fail with one or the other when installing over NFS or for
 # other permission-related reasons.  If that happens, you may want to set the
-# command to "true", which is a no-op. Note that disabling chown or chgrp
+# command to "true", which is a no-op.  Note that disabling chown or chgrp
 # will only work if setuid (or setgid) behavior is not desired or required.
 #CHOWN = chown
 #CHGRP = chgrp
+
+# Lua version
+LUA_VERSION = 5.4.8
 
 #
 # end of configuration
 #
 
-DATHELP = help hh cmdhelp history opthelp wizhelp
+DATHELP = help hh cmdhelp keyhelp history opthelp optmenu usagehlp wizhelp
 
-SPEC_LEVS = asmodeus.lev baalz.lev bigrm-*.lev castle.lev fakewiz?.lev \
-	juiblex.lev knox.lev medusa-?.lev minend-?.lev minefill.lev \
-	minetn-?.lev oracle.lev orcus.lev sanctum.lev soko?-?.lev \
-	tower?.lev valley.lev wizard?.lev \
-	astral.lev air.lev earth.lev fire.lev water.lev
-QUEST_LEVS = ???-goal.lev ???-fil?.lev ???-loca.lev ???-strt.lev
+SPEC_LEVS = asmodeus.lua baalz.lua bigrm-*.lua castle.lua fakewiz?.lua \
+	juiblex.lua knox.lua medusa-?.lua minend-?.lua minefill.lua \
+	minetn-?.lua oracle.lua orcus.lua sanctum.lua soko?-?.lua \
+	tower?.lua valley.lua wizard?.lua nhcore.lua nhlib.lua themerms.lua \
+	astral.lua air.lua earth.lua fire.lua water.lua hellfill.lua tut-?.lua
+QUEST_LEVS = ???-goal.lua ???-fil?.lua ???-loca.lua ???-strt.lua
 
-DATNODLB = $(VARDATND) license
-DATDLB = $(DATHELP) dungeon tribute $(SPEC_LEVS) $(QUEST_LEVS) $(VARDATD)
+DATNODLB = $(VARDATND) license symbols
+DATDLB = $(DATHELP) dungeon.lua tribute $(SPEC_LEVS) $(QUEST_LEVS) $(VARDATD)
 DAT = $(DATNODLB) $(DATDLB)
 
-$(GAME):
-	( cd src ; $(MAKE) )
+# These get set only if they weren't already set above or in a hints file
+#CHOWN ?= true
+#CHGRP ?= true
+#SYSCONFCREATE ?= cp sys/unix/sysconf $(INSTDIR)/sysconf
+#SYSCONFINSTALL ?= $(SYSCONFCREATE) && \
+#	 $(CHOWN) $(GAMEUID) $(INSTDIR)/sysconf && \
+#	 $(CHGRP) $(GAMEGRP) $(INSTDIR)/sysconf && \
+#	 chmod $(VARFILEPERM) $(INSTDIR)/sysconf;
+#SYSCONFENSURE ?= (if ! test -f $(INSTDIR)/sysconf ; then \
+#	 $(SYSCONFCREATE) && \
+#	 $(CHOWN) $(GAMEUID) $(INSTDIR)/sysconf && \
+#	 $(CHGRP) $(GAMEGRP) $(INSTDIR)/sysconf && \
+#	 chmod $(VARFILEPERM) $(INSTDIR)/sysconf; fi );
 
-all:	$(GAME) recover Guidebook $(VARDAT) dungeon spec_levs check-dlb
+RECOVERBIN = recover
+
+# Lua
+LUAHEADERS = lib/lua-$(LUA_VERSION)/src
+LUATESTTARGET = $(LUAHEADERS)/lua.h
+LUATOP = $(LUAHEADERS)
+LUAMAKEFLAGS = CC='$(CC)' SYSCFLAGS='$(SYSCFLAGS)'
+LUA2NHTOP = ../../..
+LUABASELIB = liblua-$(LUA_VERSION).a
+TOPLUALIB = lib/lua/$(LUABASELIB)
+
+ALLDEP = $(PRECHECK) $(GAME) recover Guidebook $(VARDAT) spec_levs check-dlb
+
+# first target is also the default target for 'make' without any arguments
+all:    $(ALLDEP)
 	true; $(MOREALL)
 	@echo "Done."
+
+$(GAME): lua_support
+	( cd src ; $(MAKE) LUA_VERSION=$(LUA_VERSION) $(GAME) )
+
+lua_support: include/nhlua.h
+	@true
+$(LUATOP)/liblua.a: $(LUAHEADERS)/lua.h
+	( cd $(LUATOP) && make $(LUAMAKEFLAGS) a )
+$(TOPLUALIB): $(LUATOP)/liblua.a
+	@( if test -d lib/lua ; then true ; else mkdir -p lib/lua ; fi )
+	cp $(LUATOP)/liblua.a $@
+
+include/nhlua.h: $(TOPLUALIB)
+	echo '/* nhlua.h - generated by top Makefile */' > $@
+	@echo '#include "../$(LUAHEADERS)/lua.h"' >> $@
+	@sed -e '/(lua_error)/!d' \
+		-e '/(lua_error)/s/LUA_API/ATTRNORETURN LUA_API/1' \
+		-e '/(lua_error)/s/;/ NORETURN;/1' < $(LUAHEADERS)/lua.h >> $@
+	@echo '#include "../$(LUAHEADERS)/lualib.h"' >> $@
+	@echo '#include "../$(LUAHEADERS)/lauxlib.h"' >> $@
+	@echo '/*nhlua.h*/' >> $@
+# LUATESTTARGET is this by default
+lib/lua-$(LUA_VERSION)/src/lua.h:
+	@echo "Please do 'make fetch-lua' in the top directory to obtain lua-$(LUA_VERSION)"
+	@false
+luabin:
+	( cd $(LUATOP) \
+	  && make $(LUAMAKEFILES) all && cd $(LUA2NHTOP) )
+
+# This is only needed for some internal tools.
+nhlua:
+	base=`ls -td lib/lua-*|head -1` ; \
+	[ -z $$base ] && $(MAKE) fetch-lua ; \
+	base=`ls -td lib/lua-*|head -1` ; \
+	cp -R $$base/ lib/nhlsrc ; \
+	rm -f util/nhlua ; \
+	( cd lib/nhlsrc && $(MAKE) clean posix ) ; \
+	cp lib/nhlsrc/src/lua util/nhlua
+
+# hints file could set LUATESTTARGET to this if GITSUBMODULES is defined
+submodules/lua/lua.h:
+	git submodule init submodules/lua
+	git submodule update submodules/lua
+#	git submodule update --remote submodules/lua
 
 # Note: many of the dependencies below are here to allow parallel make
 # to generate valid output
@@ -102,8 +186,17 @@ all:	$(GAME) recover Guidebook $(VARDAT) dungeon spec_levs check-dlb
 Guidebook:
 	( cd doc ; $(MAKE) Guidebook )
 
+Guidebook.txt:
+	( cd doc ; $(MAKE) Guidebook.txt )
+
+Guidebook.pdf:
+	( cd doc ; $(MAKE) Guidebook.pdf )
+
 manpages:
 	( cd doc ; $(MAKE) manpages )
+
+distrib:
+	( cd doc ; $(MAKE) distrib )
 
 data: $(GAME)
 	( cd dat ; $(MAKE) data )
@@ -127,25 +220,21 @@ oracles: $(GAME)
 options: $(GAME)
 	( cd dat ; $(MAKE) options )
 
-quest.dat: $(GAME)
-	( cd dat ; $(MAKE) quest.dat )
+quest.lua: $(GAME)
 
-spec_levs: dungeon
-	( cd util ; $(MAKE) lev_comp )
+spec_levs:
 	( cd dat ; $(MAKE) spec_levs )
 	( cd dat ; $(MAKE) quest_levs )
 
-dungeon: $(GAME)
-	( cd util ; $(MAKE) dgn_comp )
-	( cd dat ; $(MAKE) dungeon )
-
 nhtiles.bmp: $(GAME)
+	( cd util ; $(MAKE) tile2bmp )
 	( cd dat ; $(MAKE) nhtiles.bmp )
 
 x11tiles: $(GAME)
 	( cd util ; $(MAKE) tile2x11 )
 	( cd dat ; $(MAKE) x11tiles )
 
+# obsolete
 beostiles: $(GAME)
 	( cd util ; $(MAKE) tile2beos )
 	( cd dat ; $(MAKE) beostiles )
@@ -186,12 +275,23 @@ check-dlb: options
 
 dlb:
 	( cd util ; $(MAKE) dlb )
-	( cd dat ; ../util/dlb cf nhdat $(DATDLB) )
+	( cd dat ; LC_ALL=C ; ../util/dlb cf nhdat $(DATDLB) )
+
+wasm:
+	( cd src ; $(MAKE) CROSS_TO_WASM=1 ../targets/wasm/nethack.js )
+
+package: $(GAME) recover $(VARDAT) spec_levs
+	( cd src ;  $(MAKE) $(PACKAGE) )
 
 # recover can be used when INSURANCE is defined in include/config.h
 # and the checkpoint option is true
 recover: $(GAME)
-	( cd util ; $(MAKE) recover )
+	( cd util ; $(MAKE) $(RECOVERBIN) )
+
+# sfctool can be configured by the sysadmin to convert the savefile
+# content format as necessary.
+sfctool: $(GAME)
+	( cd util ; $(MAKE) sfctool )
 
 dofiles:
 	target=`sed -n					\
@@ -201,7 +301,6 @@ dofiles:
 		-e '}' 					\
 	  	-e '$$s/.*/nodlb/p' < dat/options` ;	\
 	$(MAKE) dofiles-$${target-nodlb}
-	(cd dat ; cp symbols $(INSTDIR) )
 	cp src/$(GAME) $(INSTDIR)
 	cp util/recover $(INSTDIR)
 	-if test -n '$(SHELLDIR)'; then rm -f $(SHELLDIR)/$(GAME); fi
@@ -220,9 +319,6 @@ dofiles:
 	if test -n '$(SHELLDIR)'; then \
 		$(CHGRP) $(GAMEGRP) $(SHELLDIR)/$(GAME); \
 		chmod $(EXEPERM) $(SHELLDIR)/$(GAME); fi
-	-( cd $(INSTDIR) ; $(CHOWN) $(GAMEUID) symbols ; \
-			$(CHGRP) $(GAMEGRP) symbols ; \
-			chmod $(FILEPERM) symbols )
 
 dofiles-dlb: check-dlb
 	( cd dat ; cp nhdat $(DATNODLB) $(INSTDIR) )
@@ -238,27 +334,121 @@ dofiles-nodlb:
 	-( cd $(INSTDIR) ; $(CHOWN) $(GAMEUID) $(DAT) ; \
 			$(CHGRP) $(GAMEGRP) $(DAT) ; \
 			chmod $(FILEPERM) $(DAT) )
+#
+# This is not part of the dependency build hierarchy.
+# It requires an explicit "make fetch-Lua".
 
-update: $(GAME) recover $(VARDAT) dungeon spec_levs
+LUA_URL :=www.lua.org/ftp
+LUA_URL_MIRROR :=www.tecgraf.puc-rio.br/lua/mirror/ftp
+LUA_URL_NHD :=www.nethack.org/download/thirdparty
+LUA_URL_list:=$(LUA_URL) $(LUA_URL_MIRROR) $(LUA_URL_NHD)
+
+fetch-lua-mirror: LUA_URL_list:=$(LUA_URL_MIRROR)
+fetch-lua-mirror: fetch-Lua
+	@true
+
+fetch-lua-nhd: LUA_URL_list:=$(LUA_URL_NHD)
+fetch-lua-nhd: fetch-Lua
+	@true
+
+fetch-lua: fetch-Lua
+	@true
+
+fetch-Lua:
+	@( \
+	  shac1=`command -v shasum`; \
+	  shac2=`command -v sha256sum`; \
+	  if [ ! -z $$shac1 ]; then \
+	    shac="$$shac1 -a 256"; elif [ ! -z $$shac2 ]; then \
+	    shac=$$shac2; else echo "CAUTION: no way to check integrity"; \
+	  fi; \
+	  set -- DUMMY $(LUA_URL_list); \
+	  luafile=lua-$(LUA_VERSION).tar.gz; \
+	  export curlstatus=1; \
+	  mkdir -p lib && cd lib && \
+	  while [ $$# -gt 0 ]; do \
+	    shift; \
+	    if [ $$curlstatus -ne 0 ]; then \
+	      luaurl=https://$$1/$$luafile; \
+	      echo Trying $$luaurl; \
+	      curl -R -O $$luaurl; \
+	      curlstatus=$$?; \
+	      if [ $$curlstatus -eq 0 ]; then \
+	        if [ ! -z "$$shac" ]; then \
+		    CHKSUMS=../submodules/CHKSUMS; \
+		    CHKSUMSTMP=../submodules/CHKSUMS.tmp; \
+		    fgrep $$luafile < $$CHKSUMS > $$CHKSUMSTMP; \
+		    if [ -z $$CHKSUMSTMP ]; then \
+		      echo "Cannot check $$luafile - no checksum known"; \
+		    else \
+		      echo Checking integrity of $$luafile with $$shac; \
+		      $$shac -w --ignore-missing -c $$CHKSUMSTMP < $$luafile; \
+		    fi; \
+	        fi; \
+	        tar zxf $$luafile && \
+	        rm -f $$luafile; \
+	      fi; \
+	    fi; \
+	  done; \
+	  true )
+
+# remove include/nhlua.h in case it was created for some other Lua version
+	@( if test -f include/nhlua.h ; then \
+	     rm -f include/nhlua.h && echo 'rm include/nhlua.h' ; fi )
+
+fetch-lua-http:
+	( mkdir -p lib && cd lib && \
+	  curl -R -O http://$(LUA_URL)/lua-$(LUA_VERSION).tar.gz && \
+	  tar zxf lua-$(LUA_VERSION).tar.gz && \
+	  rm -f lua-$(LUA_VERSION).tar.gz )
+
+#
+# This is not part of the dependency build hierarchy.
+# It requires an explicit "make fetch-docs".
+fetch-docs:
+	@FDroot=https://www.nethack.org; \
+	FDvmajor=`awk '/VERSION_MAJOR/{print $$3}' < include/patchlevel.h`; \
+	FDvminor=`awk '/VERSION_MINOR/{print $$3}' < include/patchlevel.h`; \
+	RDIR="NetHack-$${FDvmajor}.$${FDvminor}"; \
+	echo "Fetching directory information for $${RDIR}"; \
+	RDOCFILES=`curl --no-progress-meter $${FDroot}/cgi-bin/lsautodocs?$$RDIR`; \
+	FDbase="$${FDroot}/autodocs/$${RDIR}"; \
+	set -- $${RDOCFILES}; \
+	echo "Fetching $$# files"; \
+	while [ $$# -gt 0 ]; do \
+	  echo "Downloading: '$$1' from '$${FDbase}/$$1'"; \
+	  curl --no-progress-meter -R $${FDbase}/$$1 -o doc/$$1; \
+	  shift; \
+	done
+
+makedefs:
+	( cd util ; $(MAKE) makedefs )
+
+stripbs:
+	( cd util ; $(MAKE) stripbs )
+
+# 'make update' can be used to install a revised version after making
+# customizations or such.  Unlike 'make install', it doesn't delete everything
+# from the target directory to have a clean start.
+update: $(PRECHECK) $(GAME) recover $(VARDAT) spec_levs sys/unix/sysconf
 #	(don't yank the old version out from under people who're playing it)
 	-mv $(INSTDIR)/$(GAME) $(INSTDIR)/$(GAME).old
-#	quest.dat is also kept open and has the same problems over NFS
-#	(quest.dat may be inside nhdat if dlb is in use)
-	-mv $(INSTDIR)/quest.dat $(INSTDIR)/quest.dat.old
 	-mv $(INSTDIR)/nhdat $(INSTDIR)/nhdat.old
 # set up new versions of the game files
 	( $(MAKE) dofiles )
-# touch time-sensitive files
-	-touch -c $(VARDIR)/bones* $(VARDIR)/?lock* $(VARDIR)/wizard*
-	-touch -c $(VARDIR)/save/*
+# should already be present, but make sure
 	touch $(VARDIR)/perm $(VARDIR)/record
+# sysconf, but only if it does not exist
+	true; $(SYSCONFENSURE)
+# other steps from hints file
+	true; $(POSTUPDATE)
 # and a reminder
 	@echo You may also want to install the man pages via the doc Makefile.
 
 rootcheck:
 	@true; $(ROOTCHECK)
 
-install: rootcheck $(GAME) recover $(VARDAT) dungeon spec_levs
+install: rootcheck $(PRECHECK) $(GAME) recover $(VARDAT) spec_levs sys/unix/sysconf
 	true; $(PREINSTALL)
 # set up the directories
 # not all mkdirs have -p; those that don't will create a -p directory
@@ -275,10 +465,14 @@ install: rootcheck $(GAME) recover $(VARDAT) dungeon spec_levs
 # set up the game files
 	( $(MAKE) dofiles )
 # set up some additional files
-	touch $(VARDIR)/perm $(VARDIR)/record $(VARDIR)/logfile $(VARDIR)/xlogfile
-	-( cd $(VARDIR) ; $(CHOWN) $(GAMEUID) perm record logfile xlogfile ; \
-			$(CHGRP) $(GAMEGRP) perm record logfile xlogfile ; \
-			chmod $(VARFILEPERM) perm record logfile xlogfile )
+	touch $(VARDIR)/perm $(VARDIR)/record $(VARDIR)/logfile $(VARDIR)/xlogfile \
+         $(VARDIR)/livelog
+	-( cd $(VARDIR) ; $(CHOWN) $(GAMEUID) perm record logfile xlogfile livelog ; \
+			$(CHGRP) $(GAMEGRP) perm record logfile xlogfile livelog ; \
+			chmod $(VARFILEPERM) perm record logfile xlogfile livelog )
+# sysconf
+	true; $(SYSCONFINSTALL)
+# other steps from hints file
 	true; $(POSTINSTALL)
 # and a reminder
 	@echo You may also want to reinstall the man pages via the doc Makefile.
@@ -286,15 +480,32 @@ install: rootcheck $(GAME) recover $(VARDAT) dungeon spec_levs
 
 # 'make clean' removes all the .o files, but leaves around all the executables
 # and compiled data files
-clean:
+clean: clean-lib clean-keep-lib
+	@true
+
+clean-lib:
+	-( cd $(LUATOP) && $(MAKE) clean )
+
+clean-keep-lib:
 	( cd src ; $(MAKE) clean )
 	( cd util ; $(MAKE) clean )
+	( cd dat ; $(MAKE) clean )
 	( cd doc ; $(MAKE) clean )
 
 # 'make spotless' returns the source tree to near-distribution condition.
 # it removes .o files, executables, and compiled data files
-spotless:
+spotless:: spotless-lib spotless-keep-lib
+	@true
+
+spotless-lib:: clean-lib
+	-( cd lib/lua && rm $(LUABASELIB) )
+
+spotless-keep-lib: clean-keep-lib
 	( cd src ; $(MAKE) spotless )
 	( cd util ; $(MAKE) spotless )
 	( cd dat ; $(MAKE) spotless )
 	( cd doc ; $(MAKE) spotless )
+spotless-clean-submodule:
+	@( if test -f submodules/lua/lua.h ; then \
+	    git submodule deinit submodules/lua ; fi )
+
